*** TODOs

Price/origin checks on olive oil around Villeray. 10$/1L refillable
bottle?

Hemp seeds:
- Call back merci and ask what "Protection" means, and say that we
  won't buy any more until we know where they come from.
- Still waiting for email response from Manitoba Harvest.
- Call back Jacques the boss at Aliments Trigone.
- Call Lufa and find out if they know where their hemp seeds come from
  (Matt at Yupik said either Manitoba or China).
- Check who certified these products organic, and ask the
  certification agency if they know where the hemp seeds were grown.
- Start by looking for hemp farms near us, and ask those farmers who
  they sell to.

Eggs:
- Price/origin checks in local epiceries.

Maple syrup:
- Call Eloi Beauregard (No Permis 3044) (450)797-2300 and ask if he
  has the maple trees or if he just transforms the sap into syrup.
- Make a map comparing Eloi and Crepuscule.

** 21 Dec 2015

New idea: write down all information in .org files, organized into at
least two sub-directories:
- places: stores, factories, and farms.
- products: things you can buy.

Each places/*.org file may have a Buys From or Delivers To table 

** 11 Dec 2015

[[https://www.importgenius.com/how-it-works][ImportGenius]] has a paid-access database of all products imported and
exported in the US. Their data source is apparently public record, but
how to obtain?

[[http://www.achetonsquebecois.com/][AchetonsQuebecois]] has some public web pages that list vendors of good
Made In Quebec.

This project is trying to establish [[https://en.wikipedia.org/wiki/Chain_of_custody][Chain of custody]].

Quebec Vrai has [[http://www.quebecvrai.org/membres?statut=0&entreprise=puscule][3 records]] for Ferme Le Crepuscule. For example [[http://www.quebecvrai.org/upload/contenu-fichiers/pa96001-01-cert-20150513-20150513115546.pdf][maple
syrup]].

** 18 Nov 2015

*** Eggs

Crepuscule prices listed on their [[https://www.fermelecrepuscule.com/fr/produits-biologique/oeufs.html][web page]]. Interestingly, they
explain what the sizes mean:

| size (fr)  | size (en) | Crepuscule (g) | Canada (g) | USA (oz) |
|------------+-----------+----------------+------------+----------|
| jumbo      | Jumbo     |            >69 | >=70       |     >2.5 |
| extra gros | XL        |                | >=63       |    >2.25 |
| gros       | L         |          56-63 | >=56       |       >2 |
| moyen      | M         |          49-55 | >=49       |    >1.75 |
| petit      | S         |          42-49 | >=42       |     >1.5 |
|            | Peewee    |                | <42        |    >1.25 |

Weight (g) comes from the Crepuscule web page. Extra gros has a
question mark (?) since it was not listed on the web page. From
[[https://en.wikipedia.org/wiki/Chicken_egg_sizes][wikipedia:Chicken_egg_sizes]] I see that the grades are defined by the
USDA, in oz. Also Canada defines egg sizes [[http://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._284/page-17.html][on this web page]].

*** Maple syrup

Crepuscule prices listed on their [[https://www.fermelecrepuscule.com/fr/produits-biologique/erable.html][web page]].

Interesting [[http://fpaq.ca/wp-content/uploads/2015/02/InfoSirop_Juin215_Web1.pdf][InfoSirop]] 20-page PDF, including prices "en vrac." Prices:
Clair more expensive than ambree/fonce.

** 17 Nov 2015
*** Database ideas
Table of pricechecks: date, organic, store, manufacturer, CAD,
quantity, unit.

Table of conversations: date, phone number, name, product, supplier.

Table of places: need to be able to distinguish between observations
and facts that have been checked. For example we know that the
Mondiana Belanger store has hemp seeds from the Manitoba Harvest
factory, but we do not know how many middlemen there were between the
factory and the store. Visualize unchecked connections as a line
segment with a question mark.

*** Addresses 

Mondiana Belanger
1120 Rue Bélanger, Montréal, QC H2S 1H4

[[http://www.fermemichaca.com/pages/contact.html][Ferme Michaca]] -> Michaca Jean-Talon
3026, Smaill
Elgin, Qc
J0S 2E0

[[http://alimentsmerci.com/points_de_vente.php][Merci Entrepôt]] -> Merci Jean-Talon
12020, boul. Albert-Hudon
Montréal-Nord, QC
H1G 3K7 

[[http://lufa.com/en/contact.html][Lufa]] 
201-1400 Rue Antonio-Barbeau 
Montreal, QC H4N 1H5

[[http://www.yupik.ca/shopcustcontact.asp][Yupik]]
1385 Louvain Ouest
Montreal QC H4N 1G6
Canada

Manitoba Harvest
69 eagle drive winnipeg,
manitoba R2R 1V4

Aliments Trigone
93 chemin de l'Aqueduc,
Saint-François-de-la-Rivière-du-Sud, QC G0R-3A0.

*** Called Yupik +1-514-787-1600

Receptionist transferred me to Matt, who said
"on n'a pas ce type information."
canadian + chinois. ne sais pas quel produit est dispo chez lufa.
manitoba ou? chinois no idea.
Call another Yupik office
(514)381-9790 Totsimpex quality control dept.

*** Called Ferme Michaca (450) 264-4369

Elle ne sait pas de quel ferme les graines viennent.
Elle fait affaires avec une grossiste,
et elle ne peut pas me donner le nom/addresse.
Pourquoi? C'est "personnel" 
il faut faire des recherches sur internet.

*** Called aliments merci about hemp seeds

asked for nellie. are the prices correct? 177$/6kg, 295$/34kg? no:
177$/12.5lb, 295$/25lb
Bio? Yes.

Le nom de fournisseur est confidentiel. Pourquoi? "Protection."
I gave my email tdhock5@gmail.com and she said she would ask 
her boss if she can tell me the supplier list.

#+BEGIN_SRC text
Hello,

After discussion with my boss, the company doesn’t provide any
supplier information.

However, if you need nutritional information, technical information
about a specific product please send me an email or call me at
514-955-7295 ext 228.

Kindly,

Nelly
#+END_SRC

*** Manitoba Harvest script

Filled in Manitoba Harvest [[http://manitobaharvest.com/contact.html][contact form]].

Hi, how are you? My name is Toby Dylan Hocking, and I am a researcher
at McGill university in Montreal. I am researching the growers and
distributers of food products, to provide information to consumers. My
goal is to determine the entire supply chain starting at the farm and
ending in the consumer's dinner plate.

I bought your hemp seeds at Jean-Talon Market in Montreal and then I
looked for information on your web site. Your YouTube video claimed
that you buy hemp seeds from over 125 farmers. Can you please send me
the addresses of these farmers? I would like to make a map that shows
where exactly the farms are located.

If you are unable to provide addresses for all of your farmers, then
could you at least provide addresses for two or three of your farmers?
If you can't do that, can you please explain why you do not wish to
share this information with the consumer?

Thanks in advance and have a nice day!

*** Generic telephone scripts

*Introduction to the research project:* Hi, how are you? My name is
Toby Dylan Hocking, and I am a researcher at McGill university in
Montreal. I am researching the growers and distributers of food
products, to provide information to consumers. My goal is to determine
the entire supply chain starting at the farm and ending in the
consumer's dinner plate.

*From me to you:* I bought hemp seeds at Jean-Talon Market and I saw
your phone number on the packaging. Can you please tell me from who
you bought the hemp seeds?

*Positive response, details:* is your supplier a farmer?

*Negative response, why:* OK, can you please explain why you do not
wish to share this information with the consumer?

*Introduction au projet de recherche:* Bonjour, ça va bien ? Je
m'appelle Toby Dylan Hocking. Je suis chercheur à l'université McGill
à Montréal. Je fais une recherche sur la provenance des aliments pour
fournir des informations aux consommateurs. Ce qui m'intéresse est le
nombre d'intérmediares entre la ferme et l'assiette du consommateur.

*De moi à vous*: J'ai acheté des graines de chanvre au Marché
Jean-Talon, et j'ai vu votre numéro de téléphone sur l'emballage. S'il
vous plaît, est-ce que vous pourriez me dire de qui vous achetez vos
graines de chanvre ?

*Réponse positif, précisions:* Est-ce que votre fournisseur est la
ferme, ou une autre intérmediare ?

*Réponse négatif, pourquoi:* D'accord, est-ce que vous pourriez
m'expliquer pourquoi vous ne partager pas ces informations avec le
consommateur ?

*** Olive oil.

Olive oil? Costco Terra Delyssa Organic Extra Virgin Olive Oil,
12.99/2L (usually 14.99/2L).

[[http://www.terradelyssa.com/product/get/tplParam/3/language/en][Terra Delyssa web site]] price US$14.99/1L (irrelevant)

** 16 Nov 2015
*** Hemp seeds price checks

Hemp seeds at Mondiana Belanger:
- Manitoba Harvest from 2.49/56g to 52.99/2.27kg, 
- Aliments Trigone from 3.89/100g to 14.49/454g.

TODO call Manitoba Harvest (800) 665-4367, 69 eagle drive winnipeg,
manitoba R2R 1V4. Their [[https://www.youtube.com/watch?v=8lBTILYe4Rw][video]] says that they get the hemp seeds from
over 125 farmers.

*** Hemp seeds origin checks

Called Aliments Trigone (877) 259-7491. Talked to Cathy LEMONDE about
where their hemp seeds come from. She said they come from either the
Canadian West, or from Quebec. When I asked her if she could tell me
the names of the farms that she buys from, she told me that
information is "confidential." She told me I could call back and ask
her boss Jacques. 93, chemin de l'Aqueduc,
Saint-François-de-la-Rivière-du-Sud, AC Canada, G0R-3A0. (418)
259-7414 bio@alimentstrigone

Called Ferme Michaca (450) 264-4369 but nobody picked up. Their
package says 7.55$/250g.

Called Aliments Merci (514) 955-7295 and I left a message on an
answering machine. Left a message and Nellie 955-7295 called back with
prices: 177/6kg, 295$/34kg.

Lufa's [[https://montreal.lufa.com/en/superMarket/product/slug/3603-graines-de-chanvre-bios/id/3603][hemp seeds web page]] says that sell them for 4$/100g and they
come from Yupik. Their [[http://www.yupik.ca/products/10019-ORGANIC-HULLED-HEMP-SEEDS/][hemp seeds web page]] says they sell them for
16.79$/lb. TODO call them and ask where they get them +1-514-787-1600,
1-855-449-8745.
